[package]
name = "thundr"
version = "0.1.0"
authors = ["Austin Shafer <ashafer@badland.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils={path="../utils"}
ash="0.30.0"
bitflags=""
cgmath="0.17"
memoffset="0.5"
serde = { version="1.0", features=["derive"] }
bincode="1.2.1"
nix="0.17"
anyhow=""

# The following are only for the window system features
winit={version = "0.24", optional = true }
metal={version = "", optional = true }
objc={version = "", optional = true }
cocoa={version = "", optional = true }
wayland-client={features=["use_system_lib"], optional = true}

[features]
xcb = ["winit"]
macos = ["winit", "cocoa", "metal", "objc"]
wayland = ["wayland-client"]
