[package]
name = "wayc"
version = "0.1.0"
authors = ["ashafer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils={path="../utils"}
wayland-client={features=["use_system_lib"]}
anyhow = ""
nix = ""
libc = ""
