// Wayland binding fun fun fun
//
//
// Austin Shafer - 2019

// Supported protocols
pub mod compositor;
mod surface;
mod atmosphere;
mod shm;
mod xdg_shell;
mod wl_shell;
mod linux_dmabuf;

// Utils
mod role;
pub mod sys;
pub mod task;

// Generated by wayland-scanner
mod protocol;
