// Wayland binding fun fun fun
//
//
// Austin Shafer - 2019

// Supported protocols
pub mod compositor;
pub mod surface;
mod shm;
pub mod seat;
mod keyboard;
mod pointer;
pub mod xdg_shell;
mod wl_shell;
mod wl_output;
mod wl_subcompositor;
pub mod linux_dmabuf;
mod wl_region;

// Utils
pub mod utils;
pub mod role;
pub mod sys;
pub mod task;

// Generated by wayland-scanner
mod protocol;
